import type { Vehicle, Route, Service, Review, FAQ, GLocation, SelfDriveVehicle } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "dzire",
    image: "/images/taxi/dzire.jpg",
    name: "Maruti Dzire",
    type: "Sedan",
    category: "taxi",
    capacity: 4,
    luggage: 3,
    ac: true,
    transmission: "Manual",
    fuelType: "Petrol/CNG",
    color: "#1a365d",
    pricePerKm: 12,
    hourlyPrice: 200,
    packages: { "8hr80km": 1800, "12hr120km": 2500 },
    features: ["AC", "Music System", "Phone Charger", "Bottled Water"],
    bestFor: ["Airport Transfer", "City Tours", "2–4 People"],
    description: "Comfortable sedan perfect for airport transfers and city tours. Spacious for 4 passengers with 3 pieces of luggage.",
    tagline: "Smart Sedan for Airport & City Trips",
    longDescription: "The Maruti Dzire is Goa's most popular taxi choice for good reason. This dependable sedan combines comfort, fuel efficiency, and affordability into one smart package. With a spacious cabin for up to 4 passengers and a generous boot for 3 standard suitcases, the Dzire handles everything from quick airport runs to full-day sightseeing tours across Goa.\n\nPowered by a smooth petrol or CNG engine, the Dzire delivers consistent performance on Goa's coastal roads and national highways alike. The well-maintained interior stays cool even in peak summer heat — powerful air conditioning that actually works makes all the difference on a 32°C beach day in Goa. Charging ports keep your devices powered throughout long trips.\n\nWhether you're heading to Mopa airport at 5 AM or exploring every beach from Candolim to Vagator, the Dzire gets you there without fuss. It's the no-nonsense choice for solo travellers, couples, and small families who want reliable, clean transport at the most competitive price point in Goa.",
    specifications: {
      "Seating Capacity": "4 Passengers",
      "Luggage Space": "3 Large Bags (378L boot)",
      "Transmission": "Manual 5-Speed",
      "Fuel Type": "Petrol / CNG",
      "Air Conditioning": "Front & Rear Cooling",
      "Model Year": "2022–2024",
      "Colour Options": "White / Silver",
    },
    airportRates: { mopa: 1200, dabolim: 1500 },
    popularRoutes: [
      { route: "Mopa Airport → North Goa Hotels", price: 1200 },
      { route: "Dabolim Airport → North Goa", price: 1500 },
      { route: "8hr / 80km Local Package", price: 1800 },
      { route: "12hr / 120km Local Package", price: 2500 },
      { route: "North Goa Full Day Sightseeing", price: 2500 },
      { route: "Calangute → Dudhsagar Falls", price: 3500 },
    ],
    relatedVehicles: ["ertiga", "innova-crysta"],
    vehicleFaq: [
      { q: "How many people can fit in the Dzire?", a: "The Dzire comfortably seats 4 passengers plus the driver. It's ideal for couples and small families with up to 3 large suitcases in the boot." },
      { q: "Is there enough luggage space in the Dzire?", a: "The Dzire has a 378-litre boot — enough for 3 large suitcases. For 4 passengers with more luggage, we recommend upgrading to the Ertiga." },
      { q: "What if the Dzire breaks down mid-trip?", a: "We maintain a 24/7 breakdown support line and a backup vehicle policy. If any issue arises, a replacement will reach you within 30–45 minutes at no extra charge." },
      { q: "Can I request a specific Dzire driver?", a: "If you've traveled with us before and prefer a specific driver, mention it when booking. We'll do our best to assign them, subject to availability." },
      { q: "Are there any hidden charges for Dzire rides?", a: "No hidden charges. The quoted price includes fuel, driver, and AC. Toll charges on outstation trips are extra (paid at booths). Parking fees at venues are extra if applicable." },
    ],
  },
  {
    id: "ertiga",
    image: "/images/taxi/ertiga.jpg",
    name: "Maruti Ertiga",
    type: "SUV",
    category: "taxi",
    capacity: 6,
    luggage: 4,
    ac: true,
    transmission: "Manual",
    fuelType: "Petrol/CNG",
    color: "#2a5298",
    pricePerKm: 16,
    hourlyPrice: 280,
    packages: { "8hr80km": 2500, "12hr120km": 3500 },
    features: ["AC", "Music System", "6 Seater", "Spacious Boot"],
    bestFor: ["Family Trips", "Group of 5–6", "Long Tours"],
    description: "Spacious 6-seater SUV ideal for family trips and group outings across Goa.",
    tagline: "Spacious SUV for Families & Groups of 6",
    longDescription: "The Maruti Ertiga is the gold standard for family travel in Goa. This 6-seater SUV hits the sweet spot between space and economy — wide enough for a family with full luggage, yet nimble enough to navigate North Goa's coastal lanes and South Goa's quieter roads. It's consistently the most popular group vehicle in our fleet.\n\nWith 3-row seating, every passenger gets a proper seat with adequate legroom — no cramped middle perches. The spacious boot handles 4 large suitcases comfortably, and dual-zone AC keeps all three rows cool on Goa's hottest days. The Ertiga's petrol or CNG engine is fuel-efficient and well-suited to both short transfers and longer outstation runs.\n\nWhether you're doing a full-day North Goa sightseeing tour, heading to Dudhsagar for the day, or transferring your family from Mopa airport, the Ertiga delivers exactly what it promises: reliable space for up to 6 people at a very reasonable price. It's the smart upgrade from the Dzire when the group is larger.",
    specifications: {
      "Seating Capacity": "6 Passengers",
      "Luggage Space": "4 Large Bags",
      "Transmission": "Manual 5-Speed",
      "Fuel Type": "Petrol / CNG",
      "Air Conditioning": "Dual Zone Cooling",
      "Model Year": "2022–2024",
      "Colour Options": "White / Silverstone",
    },
    airportRates: { mopa: 1500, dabolim: 1800 },
    popularRoutes: [
      { route: "Mopa Airport → North Goa Hotels", price: 1500 },
      { route: "Dabolim Airport → North Goa", price: 1800 },
      { route: "8hr / 80km Local Package", price: 2500 },
      { route: "12hr / 120km Local Package", price: 3500 },
      { route: "North Goa Full Day Sightseeing", price: 3000 },
      { route: "Calangute → Dudhsagar Falls", price: 4500 },
    ],
    relatedVehicles: ["dzire", "innova-crysta", "tempo-traveller-12"],
    vehicleFaq: [
      { q: "Does the Ertiga have enough room for 6 passengers?", a: "Yes. The Ertiga has 3 rows with proper seating for 6 passengers. All seats have adequate legroom. For maximum comfort on long trips, 5 adults is ideal." },
      { q: "How much luggage does the Ertiga hold?", a: "With all seats occupied, the boot holds 4 large bags. If some seats are free, you can fold the third row for significantly more storage." },
      { q: "Is the Ertiga good for the Dudhsagar trip?", a: "Absolutely — the Ertiga is one of our most popular choices for the Dudhsagar trip. It's comfortable for the 2.5-hour journey and has space for beach bags and extra gear." },
      { q: "Can the Ertiga do outstation trips to Mumbai?", a: "Yes, we use the Ertiga for outstation runs to Mumbai, Pune, and Bangalore. The quoted outstation rate is ₹16/km plus ₹500 driver allowance per day." },
      { q: "Are there AC vents in all rows of the Ertiga?", a: "Yes. The Ertiga has AC vents in the front dashboard and dedicated rear vents for the second and third rows, so all passengers stay cool." },
    ],
  },
  {
    id: "innova-crysta",
    image: "/images/taxi/innova-crysta.jpg",
    name: "Toyota Innova Crysta",
    type: "Premium SUV",
    category: "taxi",
    capacity: 7,
    luggage: 5,
    ac: true,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "#1e3a5f",
    pricePerKm: 20,
    hourlyPrice: 350,
    packages: { "8hr80km": 3500, "12hr120km": 4500 },
    features: ["Premium AC", "Captain Seats", "Leather Seats", "Music System"],
    bestFor: ["Long Trips", "Premium Travel", "Corporate"],
    description: "Premium 7-seater SUV with luxury interiors. Perfect for VIPs, long outstation trips, and corporate travel.",
    tagline: "Premium SUV for Comfort & Long Journeys",
    longDescription: "The Toyota Innova Crysta is the benchmark for premium taxi travel in India, and ZipGoa's Innova fleet lives up to every expectation. With automatic transmission, leather captain seats, and whisper-quiet diesel power, the Innova Crysta delivers a travel experience that's genuinely above ordinary — you feel the difference from the moment you settle into your seat.\n\nSeven passengers travel in real comfort — there are no cramped middle rows here. Premium rear AC vents keep the entire cabin cool across all three rows on Goa's hottest days. The automatic gearbox makes long journeys smoother and less taxing for the driver, translating into a more relaxed ride for every passenger. High ground clearance handles Goa's varied road conditions with confident authority.\n\nChoose the Innova Crysta for corporate airport pickups, VIP travel, longer outstation journeys to Mumbai or Pune, or simply when you want the best vehicle available. Once you've experienced an Innova on a long drive, the difference over ordinary sedans and SUVs is obvious and worth every rupee.",
    specifications: {
      "Seating Capacity": "7 Passengers",
      "Luggage Space": "5 Large Bags",
      "Transmission": "Automatic",
      "Fuel Type": "Diesel",
      "Air Conditioning": "Triple Zone Premium AC",
      "Model Year": "2023–2024",
      "Colour Options": "White Pearl / Black",
    },
    airportRates: { mopa: 2000, dabolim: 2200 },
    popularRoutes: [
      { route: "Mopa Airport → North Goa Hotels", price: 2000 },
      { route: "Dabolim Airport → North Goa", price: 2200 },
      { route: "8hr / 80km Local Package", price: 3500 },
      { route: "12hr / 120km Local Package", price: 4500 },
      { route: "Goa → Mumbai (Outstation)", price: 14000 },
      { route: "Calangute → Dudhsagar Falls", price: 5500 },
    ],
    relatedVehicles: ["ertiga", "tempo-traveller-12", "urbania-17"],
    vehicleFaq: [
      { q: "Is the Innova Crysta automatic or manual?", a: "Our Innova Crysta fleet is fully automatic — perfect for long highway drives like Goa to Mumbai or Pune. The smooth automatic gearbox reduces fatigue on long stretches." },
      { q: "How many seats does the Innova Crysta have?", a: "The Innova Crysta seats 7 passengers plus the driver in 3 rows. All rows have comfortable, spacious seats — no compromise on legroom in any row." },
      { q: "Does the Innova have AC for all rows?", a: "Yes. The Innova Crysta has triple-zone premium AC with dedicated vents for all three rows, ensuring everyone stays cool regardless of where they sit." },
      { q: "Is the Innova Crysta suitable for Goa to Mumbai?", a: "Absolutely — the Innova Crysta is our most recommended vehicle for the Goa–Mumbai or Goa–Pune run. Comfortable for 10–11 hours, spacious, and reliable on highways." },
      { q: "What are the extra charges for outstation trips in the Innova?", a: "Outstation rate is ₹20/km. Additional charges: driver food allowance ₹500/day, night halt ₹500/night, toll charges extra (paid at booths), parking extra if applicable." },
    ],
  },
  {
    id: "tempo-traveller-12",
    image: "/images/taxi/tempo-traveller-12.jpg",
    name: "Tempo Traveller 12 Seater",
    type: "Van",
    category: "taxi",
    capacity: 12,
    luggage: 8,
    ac: true,
    color: "#2d5a8e",
    pricePerKm: 25,
    packages: { "8hr80km": 4000, "12hr120km": 5500 },
    features: ["AC", "Push Back Seats", "Music System", "LED Lights"],
    bestFor: ["Group Tours", "Family Outing", "10–12 People"],
    description: "Comfortable 12-seater van with push-back seats — great for group sightseeing and family outings.",
    tagline: "12-Seater for Group Tours & Family Outings",
    longDescription: "The Tempo Traveller 12-Seater is our most popular group vehicle for tours across Goa. With push-back seats arranged in a 2+1 configuration, each passenger has genuine comfort — not just a flat bench. Overhead luggage racks and under-seat storage accommodate the group's bags without cluttering the aisle.\n\nPowerful roof-mounted AC keeps all 12 passengers cool even in peak Goa heat. The music system with aux/bluetooth connectivity means your group's playlist plays throughout the journey. LED ambient lighting adds a pleasant touch on evening transfers. The high roof provides comfortable headroom for standing while boarding.\n\nWhether your group is exploring North Goa's beaches, heading to Dudhsagar for the day, or transferring from the airport to your resort, the 12-seater Tempo Traveller delivers. It's far more comfortable than splitting into multiple smaller vehicles — everyone travels together, and the total cost is significantly lower per head.",
    specifications: {
      "Seating Capacity": "12 Passengers",
      "Luggage Space": "8 Large Bags (overhead + boot)",
      "Transmission": "Manual",
      "Fuel Type": "Diesel",
      "Air Conditioning": "Powerful Roof-Mounted AC",
      "Model Year": "2022–2024",
      "Colour Options": "White",
    },
    airportRates: { mopa: 2500, dabolim: 2800 },
    popularRoutes: [
      { route: "Mopa Airport → Group Hotels", price: 2500 },
      { route: "Dabolim Airport → Group Hotels", price: 2800 },
      { route: "8hr / 80km Local Package", price: 4000 },
      { route: "12hr / 120km Local Package", price: 5500 },
      { route: "Full Day North or South Goa Tour", price: 5500 },
      { route: "Goa → Mumbai (Outstation)", price: 18000 },
    ],
    relatedVehicles: ["ertiga", "tempo-traveller-14", "innova-crysta"],
    vehicleFaq: [
      { q: "Is the 12-seater Tempo Traveller comfortable for 12 passengers?", a: "Yes. Push-back seats in a 2+1 layout give everyone proper legroom and recline. It's significantly more comfortable than regular minibuses." },
      { q: "How much luggage does the 12-seater hold?", a: "Overhead racks plus the rear boot together accommodate 8 large bags. For a 12-person group with full luggage, we may recommend a separate luggage vehicle or the 14-seater." },
      { q: "Does the 12-seater have AC?", a: "Yes — powerful roof-mounted AC units cool the entire vehicle efficiently. The system is serviced regularly to handle Goa's peak summer heat." },
      { q: "Can the Tempo Traveller do the Dudhsagar trip?", a: "Yes, we do the Dudhsagar trip in the 12-seater regularly. Note that the jeep safari inside the sanctuary is still separate (₹600/person) as private vehicles aren't allowed inside." },
      { q: "Is there a music system in the Tempo Traveller?", a: "Yes — a quality sound system with aux and Bluetooth connectivity. Your group can play its own playlist throughout the journey." },
    ],
  },
  {
    id: "tempo-traveller-14",
    image: "/images/taxi/tempo-traveller-17.jpg",
    name: "Tempo Traveller 14 Seater",
    type: "Van",
    category: "taxi",
    capacity: 14,
    luggage: 10,
    ac: true,
    color: "#2d5a8e",
    pricePerKm: 28,
    packages: { "8hr80km": 4500, "12hr120km": 6000 },
    features: ["AC", "Push Back Seats", "Music System", "Large Boot"],
    bestFor: ["Large Groups", "Tour Packages", "12–14 People"],
    description: "14-seater tempo traveller ideal for larger groups exploring Goa comfortably.",
    tagline: "14-Seater for Larger Group Adventures",
    longDescription: "When your group is between 12 and 14 people, the Tempo Traveller 14-Seater is the perfect fit — everyone travels together in one comfortable vehicle without paying for a full mini-bus. With a longer wheelbase than the 12-seater, the 14-seater provides even more legroom per row and a substantially larger boot for group luggage.\n\nPush-back seats with proper cushioning ensure that even on longer journeys to Dudhsagar or outstation trips, passengers arrive refreshed rather than stiff. Dual roof-mounted AC units cover every row effectively. The expanded boot is particularly useful for airport transfers where 14 passengers typically have significant luggage.\n\nGroups using the 14-seater often comment that it's the best value option for mid-sized groups — more economical per head than booking two 7-seater Innovas, yet providing the same standard of comfort with the added benefit of the entire group traveling together.",
    specifications: {
      "Seating Capacity": "14 Passengers",
      "Luggage Space": "10 Large Bags",
      "Transmission": "Manual",
      "Fuel Type": "Diesel",
      "Air Conditioning": "Dual Roof-Mounted AC",
      "Model Year": "2022–2024",
      "Colour Options": "White",
    },
    airportRates: { mopa: 3000, dabolim: 3500 },
    popularRoutes: [
      { route: "Mopa Airport → Group Hotels", price: 3000 },
      { route: "Dabolim Airport → Group Hotels", price: 3500 },
      { route: "8hr / 80km Local Package", price: 4500 },
      { route: "12hr / 120km Local Package", price: 6000 },
      { route: "Full Day Sightseeing Tour", price: 6000 },
      { route: "Goa → Mumbai (Outstation)", price: 22000 },
    ],
    relatedVehicles: ["tempo-traveller-12", "tempo-traveller-20"],
    vehicleFaq: [
      { q: "What's the difference between 12-seater and 14-seater Tempo Travellers?", a: "The 14-seater has a longer chassis with 2 extra seats, more legroom per row, and a larger boot. It's slightly more expensive but the upgrade in space is noticeable on longer trips." },
      { q: "Is the 14-seater Tempo Traveller good for airport transfers?", a: "Yes — it's ideal for group airport pickups with significant luggage. The larger boot handles 10 large bags comfortably alongside the overhead rack storage." },
      { q: "Can we play music in the 14-seater?", a: "Yes. The 14-seater has a Bluetooth/aux sound system. Your group can connect a phone and play your own playlists throughout the journey." },
      { q: "How long does a Goa to Mumbai trip take in the 14-seater?", a: "Goa to Mumbai is approximately 580km and takes 10–11 hours by road. The 14-seater is well-suited for this run with regular comfort stops every 2–3 hours." },
      { q: "Are there extra charges for tolls in the 14-seater?", a: "Yes. Toll charges are paid at booths and are extra on all outstation trips. We'll give you an approximate toll estimate before you book." },
    ],
  },
  {
    id: "tempo-traveller-20",
    image: "/images/taxi/tempo-traveller-20.jpg",
    name: "Tempo Traveller 20 Seater",
    type: "Mini Bus",
    category: "taxi",
    capacity: 20,
    luggage: 15,
    ac: true,
    color: "#1a3a6b",
    pricePerKm: 35,
    packages: { "8hr80km": 5500, "12hr120km": 7500 },
    features: ["AC", "Reclining Seats", "Sound System", "Overhead Storage"],
    bestFor: ["Large Groups", "Corporate Events", "Pilgrimages"],
    description: "Mini bus seating 20 passengers — perfect for large group travel, corporate outings, and pilgrimages.",
    tagline: "20-Seater Mini Bus for Large Groups",
    longDescription: "When 20 people need to travel together in comfort, our Tempo Traveller 20-Seater delivers exactly what's needed — a spacious, air-conditioned mini bus with reclining seats and the power to handle Goa's roads and national highways with ease. It's the most economical per-head option for large groups visiting Goa.\n\nThe reclining seat configuration provides comfort that genuinely rivals smaller vehicles. Dedicated overhead storage for every row means personal bags are always within reach. Multi-unit AC provides powerful cooling throughout the vehicle length, so even rear-row passengers stay comfortable on the hottest Goa afternoons. The premium sound system with bluetooth connectivity keeps group spirits high throughout the journey.\n\nCorporate groups on team outings, pilgrimages to Goa's temples and churches, and large family reunions all benefit from keeping everyone in one vehicle. Coordination is simpler, costs are shared more effectively, and the shared journey itself becomes part of the experience.",
    specifications: {
      "Seating Capacity": "20 Passengers",
      "Luggage Space": "15 Large Bags (overhead + boot)",
      "Transmission": "Manual",
      "Fuel Type": "Diesel",
      "Air Conditioning": "Multi-Unit Powerful AC",
      "Model Year": "2022–2024",
      "Colour Options": "White",
    },
    airportRates: { mopa: 4500, dabolim: 5000 },
    popularRoutes: [
      { route: "Mopa Airport → Group Hotels", price: 4500 },
      { route: "Dabolim Airport → Group Hotels", price: 5000 },
      { route: "8hr / 80km Local Package", price: 5500 },
      { route: "12hr / 120km Local Package", price: 7500 },
      { route: "Full Day Sightseeing Tour", price: 7500 },
      { route: "Goa → Mumbai (Outstation)", price: 30000 },
    ],
    relatedVehicles: ["tempo-traveller-14", "urbania-17"],
    vehicleFaq: [
      { q: "Does the 20-seater have proper reclining seats?", a: "Yes. Our 20-seater Tempo Traveller has individual reclining seats, not fixed benches. Each passenger can adjust their seating position for comfort on longer journeys." },
      { q: "Can we travel to Mumbai or Pune in the 20-seater?", a: "Yes — our 20-seater is regularly used for outstation trips to Mumbai, Pune, and Bangalore. For groups of 15–20 people, it's the most cost-effective option for such distances." },
      { q: "Is the 20-seater suitable for corporate team outings?", a: "Absolutely. Corporate groups love the 20-seater for team outings in Goa — everyone travels together, there's space for luggage, and the AC keeps everyone comfortable for full-day tours." },
      { q: "How far in advance should I book the 20-seater?", a: "We recommend booking at least 48 hours in advance for the 20-seater, especially during peak season (November–January). For outstation trips, 72 hours advance notice is ideal." },
      { q: "Are there any restrictions on the 20-seater?", a: "No. The 20-seater can travel anywhere in Goa and interstate. For Dudhsagar, the jeep safari portion inside the sanctuary is separate as private vehicles aren't permitted inside." },
    ],
  },
  {
    id: "urbania-17",
    image: "/images/taxi/urbania-17.jpg",
    name: "Force Urbania 17 Seater",
    type: "Luxury Bus",
    category: "taxi",
    capacity: 17,
    luggage: 12,
    ac: true,
    color: "#0f2a4a",
    pricePerKm: 45,
    packages: { "8hr80km": 7500, "12hr120km": 9500 },
    features: ["Luxury AC", "Premium Seats", "Music System", "USB Charging"],
    bestFor: ["Group Tours", "Wedding Parties", "Premium Events"],
    description: "Luxury 17-seater Urbania bus — the ultimate in group travel comfort for weddings, events, and premium tours.",
    tagline: "Luxury 17-Seater Coach for Premium Events",
    longDescription: "The Force Urbania is not a standard tempo traveller — it's a purpose-built luxury coach that redefines group travel in Goa. With panoramic windows, individual USB charging ports, premium reclining seats with headrests, and a sophisticated climate control system, the Urbania offers business-class comfort for 17 passengers.\n\nThe vehicle's spacious interior has a premium feel throughout — wide aisles, generous seat pitch, and quality materials throughout. The luxury AC system maintains a consistent temperature across all zones. Individual reading lights allow night travelers to read without disturbing others. The professional-grade sound system is perfect for wedding parties and celebratory group journeys.\n\nThe Urbania is the default choice for wedding shuttles, corporate VIP transfers, upscale resort pickups, and any occasion where your group deserves more than a standard vehicle. It's also increasingly popular with high-end tour groups who spend significant time in the vehicle and value the comfort differential.",
    specifications: {
      "Seating Capacity": "17 Passengers (luxury config)",
      "Luggage Space": "12 Large Bags",
      "Transmission": "Manual",
      "Fuel Type": "Diesel",
      "Air Conditioning": "Luxury Climate Control System",
      "Model Year": "2023–2024",
      "Colour Options": "White / Silver",
    },
    airportRates: { mopa: 6000, dabolim: 7000 },
    popularRoutes: [
      { route: "Mopa Airport → Luxury Resort", price: 6000 },
      { route: "Dabolim Airport → Luxury Resort", price: 7000 },
      { route: "8hr / 80km Local Package", price: 7500 },
      { route: "12hr / 120km Local Package", price: 9500 },
      { route: "Wedding / Event Day Transfer", price: 10000 },
      { route: "Goa → Mumbai (Outstation)", price: 35000 },
    ],
    relatedVehicles: ["tempo-traveller-20", "tempo-traveller-14"],
    vehicleFaq: [
      { q: "What makes the Urbania different from a standard Tempo Traveller?", a: "The Urbania is a purpose-built luxury coach — wider seats with headrests, individual USB ports, panoramic windows, and a premium climate system. It's in a different class from standard tempo travellers." },
      { q: "Is the Urbania suitable for wedding transfers?", a: "Absolutely — it's our most popular vehicle for wedding shuttles in Goa. The premium feel, wide aisle for wedding attire, and sound system make it perfect for bridal parties and guest transfers." },
      { q: "How many people does the Urbania seat?", a: "The Urbania seats 17 passengers in full luxury configuration with wide, premium reclining seats. For events requiring more space, we can configure it for 14–15 passengers with extra legroom." },
      { q: "Can the Urbania be booked for multi-day tours?", a: "Yes. For multi-day luxury group tours in and around Goa, the Urbania is the ideal choice. We offer daily rates for multi-day bookings — WhatsApp us for custom pricing." },
      { q: "Does the Urbania have individual charging ports?", a: "Yes — every seat has a dedicated USB charging port. Passengers can keep their devices charged throughout long transfers and sightseeing tours." },
    ],
  },
  // SELF-DRIVE VEHICLES
  {
    id: "baleno",
    name: "Maruti Baleno",
    type: "Hatchback",
    category: "self-drive",
    capacity: 5,
    luggage: 3,
    ac: true,
    transmission: "Manual",
    fuelType: "Petrol",
    color: "#48bb78",
    pricePerDay: 1500,
    deposit: 5000,
    weeklyRate: 1350,
    monthlyRate: 1200,
    mileage: "21 kmpl",
    bootSpace: "318 litres",
    features: ["AC", "Music System", "ABS", "Airbags"],
    bestFor: ["Solo Travel", "Couples", "Beach Hopping"],
    description: "Zippy hatchback — ideal for solo travellers and couples exploring Goa at their own pace.",
    tagline: "Fuel-Efficient Hatchback — Freedom to Explore Goa",
    longDescription: "The Maruti Baleno is the perfect vehicle for independent travellers who want to discover Goa on their own schedule. Zippy, fuel-efficient, and easy to park everywhere from narrow Panjim lanes to crowded beach parking lots, the Baleno gives you the freedom that no taxi schedule can match. It's the car that turns a Goa holiday into a real adventure.\n\nAt 21 kmpl petrol mileage, the Baleno is kind to your budget — a full tank takes you well over 500km, more than enough for days of exploration. The 318-litre boot handles beach bags, shopping, and day-trip supplies without a problem. ABS and dual airbags provide peace of mind. The music system with bluetooth means your Goa playlist is always playing.\n\nFrom the beaches of Calangute and Anjuna to the heritage churches of Old Goa and the quiet roads of South Goa, the Baleno is your key to authentic, self-paced exploration. It's the entry point to ZipGoa's self-drive fleet — the most affordable option with no compromise on quality or reliability.",
    specifications: {
      "Seating Capacity": "5 Persons",
      "Transmission": "Manual 5-Speed",
      "Fuel Type": "Petrol",
      "Mileage": "21 kmpl",
      "Boot Space": "318 litres",
      "Air Conditioning": "Single Zone Auto",
      "Safety": "ABS + Dual Airbags",
    },
    relatedVehicles: ["hycross", "thar"],
    vehicleFaq: [
      { q: "What documents do I need to rent the Baleno?", a: "Valid driving license (original), Aadhaar card or passport, and a security deposit of ₹5,000. No international licence issues — most countries accepted with a valid DL." },
      { q: "What is the fuel policy for the Baleno?", a: "You receive the car with a full tank and must return it with a full tank. Fuel cost is entirely on the renter. The Baleno's excellent mileage of 21 kmpl keeps fuel costs very low." },
      { q: "Are there any km restrictions for the Baleno rental?", a: "We provide 200 free km per day. After 200km/day, extra km are charged at ₹10/km. Most travellers exploring Goa don't exceed 200km in a day." },
      { q: "Is the Baleno insured?", a: "Yes — comprehensive insurance is included in the rental price. In case of an accident, there's a standard excess (deductible) amount. We advise against off-road driving." },
      { q: "Can I take the Baleno outside Goa?", a: "Day trips to nearby Karnataka (Gokarna) are usually fine with advance permission. For longer outstation travel outside Goa, please notify us when booking — different rates apply." },
    ],
  },
  {
    id: "hycross",
    name: "Toyota Hycross",
    type: "SUV Hybrid",
    category: "self-drive",
    capacity: 7,
    luggage: 5,
    ac: true,
    transmission: "Automatic",
    fuelType: "Hybrid",
    color: "#38a169",
    pricePerDay: 3500,
    deposit: 10000,
    weeklyRate: 3150,
    monthlyRate: 2800,
    mileage: "21 kmpl (hybrid)",
    bootSpace: "279 litres (3rd row folded: 1083L)",
    features: ["Hybrid Engine", "Auto AC", "Sunroof", "7 Seats"],
    bestFor: ["Families", "Eco Travel", "Long Drives"],
    description: "Premium hybrid SUV combining comfort and fuel efficiency — perfect for longer explorations.",
    tagline: "Premium Hybrid SUV — Eco-Friendly Luxury for Goa",
    longDescription: "The Toyota Hycross is the most advanced vehicle in ZipGoa's self-drive fleet. This premium hybrid SUV combines 7-seat capacity, a panoramic sunroof, dual-zone automatic climate control, and Toyota's renowned hybrid powertrain — delivering remarkable 21 kmpl efficiency in a spacious SUV package. It's Goa's greenest way to travel in style.\n\nThe e-CVT automatic transmission makes the Hycross effortless to drive — smooth acceleration, no gear changing, and a serene cabin that isolates you from road noise. The sunroof transforms Goa drives into something cinematic — golden hour on the coastal highway with the roof open is simply spectacular. Cruise control makes long drives comfortable. Advanced driver assistance systems add safety on unfamiliar roads.\n\nFor families, the Hycross's 7-seat 3-row layout means everyone travels together in genuine comfort. For couples or solo travellers, folding the second and third rows creates a massive 1,083-litre cargo bay — perfect for long stays or adventure gear. This is the vehicle for discerning travellers who want the best of comfort, space, and eco-consciousness in one premium package.",
    specifications: {
      "Seating Capacity": "7 Persons (3 rows)",
      "Transmission": "e-CVT Automatic",
      "Fuel Type": "Petrol Hybrid",
      "Mileage": "21 kmpl (hybrid)",
      "Boot Space": "279L (3rd row up) / 1083L (folded)",
      "Air Conditioning": "Dual Zone Automatic",
      "Safety": "6 Airbags + ADAS",
    },
    relatedVehicles: ["baleno", "thar"],
    vehicleFaq: [
      { q: "Is the Toyota Hycross automatic or manual?", a: "The Hycross uses a smooth e-CVT automatic transmission — ideal for driving in Goa's traffic and also on open highways. There's no clutch, making it stress-free for those unfamiliar with manual driving." },
      { q: "How does the hybrid system work in practice?", a: "The hybrid system automatically switches between petrol engine and electric motor, delivering seamless power and excellent 21 kmpl efficiency. You never need to charge it — it self-charges through regenerative braking." },
      { q: "Can the Hycross drive to Dudhsagar or off-road areas?", a: "The Hycross is an urban SUV, not an off-roader. It handles Goa's roads excellently, but we advise against taking it on the rocky Dudhsagar jungle trails. The Thar is better for that purpose." },
      { q: "What is the deposit for the Toyota Hycross?", a: "The refundable security deposit for the Hycross is ₹10,000. This is returned in full upon return of the vehicle in its original condition." },
      { q: "Does the Hycross have a sunroof?", a: "Yes — the Hycross has a large panoramic sunroof. On Goa's scenic coastal highways, it creates a fantastic open experience. The sunroof can be fully opened or just tilted." },
    ],
  },
  {
    id: "thar",
    name: "Mahindra Thar",
    type: "4x4 Adventure",
    category: "self-drive",
    capacity: 4,
    luggage: 2,
    ac: true,
    transmission: "Manual",
    fuelType: "Diesel",
    color: "#d97706",
    pricePerDay: 4500,
    deposit: 15000,
    weeklyRate: 4050,
    monthlyRate: 3600,
    mileage: "15 kmpl",
    bootSpace: "Limited (adventure configuration)",
    features: ["4x4 Drive", "Open Roof", "Off-road Tyres", "Adventure Fit"],
    bestFor: ["Adventure Travel", "Off-roading", "Dudhsagar Trail"],
    description: "The iconic 4x4 — built for adventure. Explore Goa's beaches, forests, and waterfalls in style.",
    tagline: "Iconic 4x4 — For the Adventurous Explorer",
    longDescription: "The Mahindra Thar is not just a vehicle — it's a statement. India's most iconic 4x4 turns every drive through Goa into an adventure. The removable soft-top transforms the cabin from sheltered SUV to a completely open experience in minutes, making sunset drives along Goa's coastal roads completely exhilarating.\n\nWith proper 4x4 capability, the Thar takes you where other cars simply can't go. Rocky forest trails, river crossings, beach driving, the rugged paths near Dudhsagar — the Thar handles all of it with ease and enthusiasm. The diesel engine provides serious torque for off-road conditions while delivering acceptable fuel efficiency at 15 kmpl. High ground clearance and robust suspension absorb rough terrain without drama.\n\nThe Thar is Goa's most sought-after self-drive vehicle — regularly booked weeks in advance during peak season. It attracts travellers who don't want to follow the tourist trail. If your Goa itinerary includes off-road adventure, beach driving at Morjim or Arambol, or approaching the Dudhsagar area independently, the Thar is your only serious option.",
    specifications: {
      "Seating Capacity": "4 Persons",
      "Transmission": "Manual 4x4 with 2H/4H/4L modes",
      "Fuel Type": "Diesel",
      "Mileage": "15 kmpl",
      "Boot Space": "Limited (adventure config)",
      "Air Conditioning": "Front Zone AC",
      "Safety": "ABS + Dual Airbags",
    },
    relatedVehicles: ["hycross", "baleno"],
    vehicleFaq: [
      { q: "Is the Thar hard to drive?", a: "The Thar is a manual 4x4 with a normal clutch and gear system for 2WD road use. Anyone who can drive a manual car can handle it on normal roads. The 4x4 system is engaged separately when needed off-road." },
      { q: "Can I take the Thar off-road in Goa?", a: "Yes — that's what it's designed for. Rocky trails, muddy paths, forest tracks near Dudhsagar, and beach driving are all fine. Please avoid areas with deep water crossings and always inform us of your off-road plans." },
      { q: "Can I remove the soft-top of the Thar?", a: "Yes — the soft-top is removable and we'll show you how. Open-top driving in Goa (especially sunset drives on coastal roads) is one of the Thar's signature experiences." },
      { q: "What is the deposit for the Thar?", a: "The refundable security deposit for the Thar is ₹15,000 due to its off-road capability and premium nature. This is returned in full upon vehicle return in original condition." },
      { q: "Does the Thar have AC?", a: "Yes — the Thar has front AC for the two front passengers. Rear passengers in open-top mode rely on natural airflow, which is usually preferable in Goa's weather anyway." },
    ],
  },
];

export const routes: Route[] = [
  // --- Mopa Airport ---
  { from: "Mopa Airport", to: "Calangute",       distance: 42,  duration: "1h 10m",  prices: { dzire: 1250, ertiga: 1550, innova: 2000, t12: 3500, t14: 3500, t20: 4500, urb: 6000 } },
  { from: "Mopa Airport", to: "Panjim",          distance: 32,  duration: "50m",     prices: { dzire: 1250, ertiga: 1500, innova: 2000, t12: 3500, t14: 4000, t20: 4500, urb: 7000 } },
  { from: "Mopa Airport", to: "Anjuna",          distance: 48,  duration: "1h 20m",  prices: { dzire: 1200, ertiga: 1700, innova: 2300, t12: 3500, t14: 3700, t20: 4800, urb: 6200 } },
  { from: "Mopa Airport", to: "Mapusa",          distance: 28,  duration: "40m",     prices: { dzire:  900, ertiga: 1200, innova: 1800, t12: 3500, t14: 3500, t20: 3500, urb: 5000 } },
  { from: "Mopa Airport", to: "Baga",            distance: 44,  duration: "1h 15m",  prices: { dzire: 1250, ertiga: 1600, innova: 2300, t12: 3500, t14: 3500, t20: 4500, urb: 6500 } },
  { from: "Mopa Airport", to: "Vagator",         distance: 45,  duration: "1h 15m",  prices: { dzire: 1300, ertiga: 1650, innova: 2150, t12: 3000, t14: 3500, t20: 4500, urb: 6000 } },
  { from: "Mopa Airport", to: "Arambol",         distance: 25,  duration: "35m",     prices: { dzire: 1000, ertiga: 1300, innova: 2000, t12: 3000, t14: 3000, t20: 3500, urb: 5000 } },
  { from: "Mopa Airport", to: "Margao",          distance: 80,  duration: "2h",      prices: { dzire: 2000, ertiga: 2500, innova: 3500, t12: 4500, t14: 5200, t20: 6800, urb: 8800 } },
  { from: "Mopa Airport", to: "Vasco",           distance: 72,  duration: "1h 50m",  prices: { dzire: 1900, ertiga: 2400, innova: 3000, t12: 4200, t14: 4800, t20: 6300, urb: 8200 } },
  { from: "Mopa Airport", to: "Palolem",         distance: 100, duration: "2h 30m",  prices: { dzire: 2800, ertiga: 3500, innova: 4500, t12: 6200, t14: 7200, t20: 9300, urb: 12000 } },

  // --- Dabolim Airport ---
  { from: "Dabolim Airport", to: "Calangute",    distance: 45,  duration: "1h 30m",  prices: { dzire: 1500, ertiga: 1800, innova: 2200, t12: 3200, t14: 3700, t20: 4800, urb: 6200 } },
  { from: "Dabolim Airport", to: "Panjim",       distance: 29,  duration: "45m",     prices: { dzire: 1000, ertiga: 1500, innova: 2000, t12: 3000, t14: 3000, t20: 3500, urb: 5000 } },
  { from: "Dabolim Airport", to: "Margao",       distance: 12,  duration: "35m",     prices: { dzire: 1000, ertiga: 1300, innova: 1800, t12: 3000, t14: 3000, t20: 3500, urb: 5000 } },
  { from: "Dabolim Airport", to: "Colva",        distance: 14,  duration: "25m",     prices: { dzire:  900, ertiga: 1200, innova: 1800, t12: 3000, t14: 3000, t20: 3500, urb: 5000 } },
  { from: "Dabolim Airport", to: "Palolem",      distance: 60,  duration: "1h 30m",  prices: { dzire: 2500, ertiga: 3000, innova: 3800, t12: 5200, t14: 6000, t20: 7800, urb: 10000 } },
  { from: "Dabolim Airport", to: "Anjuna",       distance: 55,  duration: "1h 40m",  prices: { dzire: 1700, ertiga: 2200, innova: 2800, t12: 4000, t14: 4600, t20: 6000, urb: 7800 } },
  { from: "Dabolim Airport", to: "Baga",         distance: 47,  duration: "1h 30m",  prices: { dzire: 1500, ertiga: 1900, innova: 2500, t12: 3500, t14: 4000, t20: 5100, urb: 7000 } },
  { from: "Dabolim Airport", to: "Vagator",      distance: 52,  duration: "1h 35m",  prices: { dzire: 1700, ertiga: 2000, innova: 2700, t12: 3800, t14: 4400, t20: 5700, urb: 7400 } },
  { from: "Dabolim Airport", to: "Mapusa",       distance: 33,  duration: "55m",     prices: { dzire: 1000, ertiga: 1300, innova: 1700, t12: 2400, t14: 2800, t20: 3600, urb: 7000 } },
  { from: "Dabolim Airport", to: "Vasco",        distance: 4,   duration: "10m",     prices: { dzire:  300, ertiga:  400, innova:  700, t12: 2000, t14: 2000, t20: 2500, urb: 3000 } },

  // --- Calangute ---
  { from: "Calangute", to: "Mopa Airport",       distance: 42,  duration: "1h 10m",  prices: { dzire: 1200, ertiga: 1550, innova: 2000, t12: 2800, t14: 3200, t20: 4200, urb: 6000 } },
  { from: "Calangute", to: "Dabolim Airport",    distance: 45,  duration: "1h 30m",  prices: { dzire: 1500, ertiga: 1800, innova: 2200, t12: 3500, t14: 3700, t20: 4800, urb: 7000 } },
  { from: "Calangute", to: "Panjim",             distance: 15,  duration: "30m",     prices: { dzire:  600, ertiga:  800, innova: 1100, t12: 1600, t14: 1900, t20: 2500, urb: 5000 } },
  { from: "Calangute", to: "Anjuna",             distance: 8,   duration: "20m",     prices: { dzire:  400, ertiga:  500, innova:  700, t12: 1000, t14: 1200, t20: 1600, urb: 2100 } },
  { from: "Calangute", to: "Mapusa",             distance: 10,  duration: "20m",     prices: { dzire:  450, ertiga:  600, innova:  800, t12: 1100, t14: 1300, t20: 1700, urb: 3500 } },
  { from: "Calangute", to: "Old Goa",            distance: 25,  duration: "45m",     prices: { dzire: 1000, ertiga: 1200, innova: 1800, t12: 3000, t14: 3200, t20: 4000, urb: 6000 } },
  { from: "Calangute", to: "Vagator",            distance: 12,  duration: "25m",     prices: { dzire:  500, ertiga:  750, innova: 1200, t12: 2000, t14: 1500, t20: 2000, urb: 2600 } },
  { from: "Calangute", to: "Margao",             distance: 50,  duration: "1h 20m",  prices: { dzire: 1600, ertiga: 2000, innova: 2600, t12: 3600, t14: 4200, t20: 5400, urb: 7000 } },
  { from: "Calangute", to: "Dudhsagar",          distance: 70,  duration: "2h",      prices: { dzire: 3500, ertiga: 4500, innova: 5500, t12: 7000, t14: 8000, t20: 10000, urb: 12000 } },
  { from: "Calangute", to: "South Goa",          distance: 55,  duration: "1h 30m",  prices: { dzire: 2500, ertiga: 3000, innova: 3500, t12: 5000, t14: 5800, t20: 7500, urb: 9800 } },

  // --- Panjim ---
  { from: "Panjim", to: "Mopa Airport",          distance: 32,  duration: "50m",     prices: { dzire:  1100, ertiga: 1500, innova: 2000, t12: 3500, t14: 4000, t20: 4500, urb: 7000 } },
  { from: "Panjim", to: "Dabolim Airport",       distance: 29,  duration: "45m",     prices: { dzire:  1000, ertiga: 1500, innova: 2000, t12: 3000, t14: 3000, t20: 3500, urb: 5500 } },
  { from: "Panjim", to: "Calangute",             distance: 15,  duration: "30m",     prices: { dzire:  800, ertiga:  1200, innova: 1500, t12: 2500, t14: 2800, t20: 3000, urb: 4000 } },
  { from: "Panjim", to: "Baga",                  distance: 17,  duration: "35m",     prices: { dzire:  800, ertiga:  1200, innova: 1500, t12: 2500, t14: 2800, t20: 3000, urb: 4000 } },
  { from: "Panjim", to: "Anjuna",                distance: 18,  duration: "35m",     prices: { dzire:  1000, ertiga: 1500, innova: 1800, t12: 2500, t14: 2800, t20: 3200, urb: 4500 } },
  { from: "Panjim", to: "Vagator",               distance: 22,  duration: "45m",     prices: { dzire:  1000, ertiga: 1500, innova: 1800, t12: 2500, t14: 2800, t20: 3200, urb: 4500 } },
  { from: "Panjim", to: "Mapusa",                distance: 13,  duration: "25m",     prices: { dzire:  550, ertiga:  800, innova: 1200, t12: 1800, t14: 2000, t20: 2800, urb: 3500 } },
  { from: "Panjim", to: "Arambol",               distance: 48,  duration: "1h 20m",  prices: { dzire: 1400, ertiga: 1800, innova: 2400, t12: 3500, t14: 3900, t20: 5100, urb: 6600 } },
  { from: "Panjim", to: "Old Goa",               distance: 10,  duration: "20m",     prices: { dzire:  500, ertiga:  900, innova: 1200, t12: 2000, t14: 2300, t20: 3000, urb: 3500 } },
  { from: "Panjim", to: "Margao",                distance: 33,  duration: "50m",     prices: { dzire: 1200, ertiga: 1500, innova: 2200, t12: 3000, t14: 3200, t20: 4000, urb: 6000 } },
  { from: "Panjim", to: "Palolem",               distance: 75,  duration: "2h",      prices: { dzire: 2500, ertiga: 3000, innova: 3500, t12: 4500, t14: 5200, t20: 6800, urb: 9000 } },
  { from: "Panjim", to: "Dudhsagar",             distance: 65,  duration: "1h 50m",  prices: { dzire: 3200, ertiga: 4000, innova: 5000, t12: 6500, t14: 7500, t20: 9500, urb: 11500 } },

  // --- Mapusa ---
  { from: "Mapusa", to: "Mopa Airport",          distance: 28,  duration: "40m",     prices: { dzire:  900, ertiga: 1200, innova: 1800, t12: 3500, t14: 3500, t20: 3500, urb: 5000 } },
  { from: "Mapusa", to: "Calangute",             distance: 10,  duration: "20m",     prices: { dzire:  450, ertiga:  600, innova:  800, t12: 1100, t14: 1300, t20: 1700, urb: 3500 } },
  { from: "Mapusa", to: "Panjim",                distance: 13,  duration: "25m",     prices: { dzire:  550, ertiga:  800, innova: 1200, t12: 1800, t14: 2000, t20: 2800, urb: 3500 } },
  { from: "Mapusa", to: "Anjuna",                distance: 12,  duration: "25m",     prices: { dzire:  500, ertiga:  650, innova:  900, t12: 1300, t14: 1500, t20: 2000, urb: 2600 } },
  { from: "Mapusa", to: "Vagator",               distance: 10,  duration: "20m",     prices: { dzire:  450, ertiga:  600, innova:  800, t12: 1100, t14: 1300, t20: 1700, urb: 2200 } },
  { from: "Mapusa", to: "Arambol",               distance: 36,  duration: "55m",     prices: { dzire: 1100, ertiga: 1400, innova: 1900, t12: 2700, t14: 3100, t20: 4000, urb: 5200 } },

  // --- Anjuna ---
  { from: "Anjuna", to: "Mopa Airport",          distance: 48,  duration: "1h 20m",  prices: { dzire: 1200, ertiga: 1700, innova: 2300, t12: 3500, t14: 3700, t20: 4800, urb: 6200 } },
  { from: "Anjuna", to: "Dabolim Airport",       distance: 55,  duration: "1h 40m",  prices: { dzire: 1700, ertiga: 2200, innova: 2800, t12: 4000, t14: 4600, t20: 6000, urb: 7800 } },
  { from: "Anjuna", to: "Panjim",                distance: 18,  duration: "35m",     prices: { dzire: 1000, ertiga: 1500, innova: 1800, t12: 2500, t14: 2800, t20: 3200, urb: 4500 } },
  { from: "Anjuna", to: "Calangute",             distance: 8,   duration: "20m",     prices: { dzire:  400, ertiga:  500, innova:  700, t12: 1000, t14: 1200, t20: 1600, urb: 2100 } },
  { from: "Anjuna", to: "Vagator",               distance: 4,   duration: "10m",     prices: { dzire:  300, ertiga:  400, innova:  600, t12:  900, t14: 1100, t20: 1500, urb: 2000 } },
  { from: "Anjuna", to: "Dudhsagar",             distance: 72,  duration: "2h 10m",  prices: { dzire: 3600, ertiga: 4600, innova: 5600, t12: 7200, t14: 8200, t20: 10200, urb: 12500 } },

  // --- Baga ---
  { from: "Baga", to: "Mopa Airport",            distance: 44,  duration: "1h 15m",  prices: { dzire: 1250, ertiga: 1600, innova: 2300, t12: 3500, t14: 3500, t20: 4500, urb: 6500 } },
  { from: "Baga", to: "Dabolim Airport",         distance: 47,  duration: "1h 30m",  prices: { dzire: 1500, ertiga: 1900, innova: 2500, t12: 3500, t14: 4000, t20: 5100, urb: 7000 } },
  { from: "Baga", to: "Panjim",                  distance: 17,  duration: "35m",     prices: { dzire:  800, ertiga: 1200, innova: 1500, t12: 2500, t14: 2800, t20: 3000, urb: 4000 } },
  { from: "Baga", to: "Anjuna",                  distance: 6,   duration: "15m",     prices: { dzire:  350, ertiga:  450, innova:  650, t12:  950, t14: 1100, t20: 1500, urb: 1950 } },
  { from: "Baga", to: "Vagator",                 distance: 10,  duration: "20m",     prices: { dzire:  450, ertiga:  600, innova:  800, t12: 1100, t14: 1300, t20: 1700, urb: 2200 } },

  // --- Vagator ---
  { from: "Vagator", to: "Mopa Airport",         distance: 45,  duration: "1h 15m",  prices: { dzire: 1300, ertiga: 1650, innova: 2150, t12: 3000, t14: 3500, t20: 4500, urb: 6000 } },
  { from: "Vagator", to: "Dabolim Airport",      distance: 52,  duration: "1h 35m",  prices: { dzire: 1700, ertiga: 2000, innova: 2700, t12: 3800, t14: 4400, t20: 5700, urb: 7400 } },
  { from: "Vagator", to: "Panjim",               distance: 22,  duration: "45m",     prices: { dzire: 1000, ertiga: 1500, innova: 1800, t12: 2500, t14: 2800, t20: 3200, urb: 4500 } },
  { from: "Vagator", to: "Anjuna",               distance: 4,   duration: "10m",     prices: { dzire:  300, ertiga:  400, innova:  600, t12:  900, t14: 1100, t20: 1500, urb: 2000 } },

  // --- Margao ---
  { from: "Margao", to: "Dabolim Airport",       distance: 12,  duration: "25m",     prices: { dzire: 1000, ertiga: 1300, innova: 1800, t12: 3000, t14: 3000, t20: 3500, urb: 5000 } },
  { from: "Margao", to: "Panjim",                distance: 33,  duration: "50m",     prices: { dzire: 1200, ertiga: 1500, innova: 2200, t12: 3000, t14: 3200, t20: 4000, urb: 6000 } },
  { from: "Margao", to: "Colva",                 distance: 6,   duration: "15m",     prices: { dzire:  300, ertiga:  400, innova:  600, t12:  900, t14: 1100, t20: 1500, urb: 2000 } },
  { from: "Margao", to: "Palolem",               distance: 38,  duration: "1h",      prices: { dzire: 1200, ertiga: 1500, innova: 2000, t12: 2800, t14: 3200, t20: 4200, urb: 5500 } },
  { from: "Margao", to: "Calangute",             distance: 50,  duration: "1h 20m",  prices: { dzire: 1600, ertiga: 2000, innova: 2600, t12: 3600, t14: 4200, t20: 5400, urb: 7000 } },
  { from: "Margao", to: "Mopa Airport",          distance: 80,  duration: "2h",      prices: { dzire: 2000, ertiga: 2500, innova: 3500, t12: 4500, t14: 5200, t20: 6800, urb: 8800 } },

  // --- Vasco ---
  { from: "Vasco", to: "Dabolim Airport",        distance: 4,   duration: "10m",     prices: { dzire:  300, ertiga:  400, innova:  700, t12: 2000, t14: 2000, t20: 2500, urb: 3000 } },
  { from: "Vasco", to: "Panjim",                 distance: 30,  duration: "45m",     prices: { dzire:  900, ertiga: 1200, innova: 1600, t12: 2200, t14: 2600, t20: 3400, urb: 4400 } },
  { from: "Vasco", to: "Margao",                 distance: 14,  duration: "25m",     prices: { dzire:  600, ertiga:  800, innova: 1100, t12: 1600, t14: 1900, t20: 2500, urb: 3200 } },
  { from: "Vasco", to: "Calangute",              distance: 48,  duration: "1h 25m",  prices: { dzire: 1500, ertiga: 1900, innova: 2400, t12: 3400, t14: 3900, t20: 5100, urb: 6600 } },

  // --- Palolem ---
  { from: "Palolem", to: "Dabolim Airport",      distance: 60,  duration: "1h 30m",  prices: { dzire: 2500, ertiga: 3000, innova: 3800, t12: 5200, t14: 6000, t20: 7800, urb: 10000 } },
  { from: "Palolem", to: "Margao",               distance: 38,  duration: "1h",      prices: { dzire: 1200, ertiga: 1500, innova: 2000, t12: 2800, t14: 3200, t20: 4200, urb: 5500 } },
  { from: "Palolem", to: "Mopa Airport",         distance: 100, duration: "2h 30m",  prices: { dzire: 2800, ertiga: 3500, innova: 4500, t12: 6200, t14: 7200, t20: 9300, urb: 12000 } },
];

export const services: Service[] = [
  { id: "airport-pickup",  image: "/images/services/airport.jpg", title: "Airport Pickup/Drop", description: "Reliable transfers from Mopa (GOX) and Dabolim (GOI) airports. Flight tracking included.", icon: "Plane", emoji: "✈️", startingPrice: 900, slug: "airport-taxi" },
  { id: "local-sightseeing", image: "/images/services/sightseeing.jpg", title: "Local Sightseeing", description: "Explore Goa's best beaches, churches, forts, and markets with our expert local drivers.", icon: "MapPin", emoji: "🏖️", startingPrice: 1800, slug: "goa-sightseeing" },
  { id: "dudhsagar",        image: "/images/services/dudhsagar.jpg", title: "Dudhsagar Trip", description: "Full-day trip to the breathtaking Dudhsagar Waterfall — one of India's tallest cascades.", icon: "Waves", emoji: "🌊", startingPrice: 3500, slug: "dudhsagar-trip" },
  { id: "self-drive",        image: "/images/services/self-drive.jpg", title: "Self-Drive Cars", description: "Freedom to explore Goa on your terms. Choose from Baleno, Hycross, or Thar 4x4.", icon: "Car", emoji: "🚗", startingPrice: 1500, slug: "self-drive" },
  { id: "north-goa-tour",   image: "/images/services/north-goa.jpg", title: "North Goa Tour", description: "Calangute, Baga, Anjuna, Chapora Fort, Vagator — the best of North Goa in one day.", icon: "Sun", emoji: "🌴", startingPrice: 2000, slug: "north-goa-tour" },
  { id: "south-goa-tour", title: "South Goa Tour", description: "Colva, Palolem, Old Goa churches, Margao — serene beaches and heritage in one tour.", icon: "Church", emoji: "🏛️", startingPrice: 2500, slug: "south-goa-tour" },
  { id: "outstation", title: "Outstation Trips", description: "Travel beyond Goa — Mumbai, Pune, Bangalore, Hampi, and more with comfortable AC cabs.", icon: "Navigation", emoji: "🗺️", startingPrice: 4000, slug: "outstation" },
  { id: "hourly-rental", title: "Hourly Packages", description: "8hr/80km or 12hr/120km packages for a full day of exploring Goa at your pace.", icon: "Clock", emoji: "⏰", startingPrice: 1800, slug: "pricing" },
];

export const reviews: Review[] = [
  { id: "1", name: "Rahul Sharma", rating: 5, text: "Excellent service! Driver was punctual and very helpful with luggage. The Innova was immaculate and AC worked perfectly. Highly recommend ZipGoa for airport transfers!", date: "March 2025", tripType: "Airport Transfer", location: "Delhi" },
  { id: "2", name: "Priya Menon", rating: 5, text: "Booked the Ertiga for a full-day sightseeing tour. Our driver knew all the best spots and even shared local tips. Will definitely book again next trip!", date: "February 2025", tripType: "North Goa Sightseeing", location: "Bangalore" },
  { id: "3", name: "James Mitchell", rating: 5, text: "Great experience with the self-drive Thar. The car was in perfect condition and the team at ZipGoa was very helpful with the pickup process. Loved exploring Goa freely!", date: "January 2025", tripType: "Self-Drive Thar", location: "UK" },
  { id: "4", name: "Ananya Krishnan", rating: 5, text: "Dudhsagar trip was amazing! Driver was professional, knew the best spots, and even waited patiently. The price was very reasonable. 10/10 would recommend!", date: "December 2024", tripType: "Dudhsagar Trip", location: "Chennai" },
  { id: "5", name: "Vikram Singh", rating: 5, text: "Booked tempo traveller for family of 12. Very comfortable, clean, and the driver was excellent. Made our Goa trip stress-free. ZipGoa is the best in Goa!", date: "November 2024", tripType: "Family Group Tour", location: "Hyderabad" },
  { id: "6", name: "Sarah Johnson", rating: 5, text: "Used ZipGoa for 5 days straight. Every driver was professional, English-speaking, and punctual. Transparent pricing with no surprises. Best taxi service in Goa!", date: "October 2024", tripType: "Multi-day Tour", location: "Australia" },
  { id: "7", name: "Anita Desai", rating: 5, text: "Booked last minute for early morning flight. Driver arrived 15 min early, helped with luggage. Smooth ride. Will use again!", date: "April 2025", tripType: "Mopa Airport Transfer", location: "Mumbai" },
  { id: "8", name: "Vikram Singh", rating: 5, text: "Family trip with 6 people. Ertiga was perfect. Driver knew amazing local spots not in any guidebook. Kids loved it!", date: "March 2025", tripType: "South Goa Tour", location: "Pune" },
  { id: "9", name: "Sarah Williams", rating: 5, text: "Rented Thar convertible for 5 days. Brand new, immaculate. No hidden charges. Amazing experience driving in Goa!", date: "February 2025", tripType: "Self-Drive Thar", location: "Australia" },
  { id: "10", name: "Ravi Krishnan", rating: 5, text: "Dudhsagar trip was highlight of Goa visit. Driver knew route perfectly, shared interesting facts. Great service!", date: "January 2025", tripType: "Dudhsagar Trip", location: "Bangalore" },
  { id: "11", name: "Pooja Mehta", rating: 5, text: "Booked Innova Crysta for honeymoon. Driver respectful, professional, knew all romantic spots. Made our trip memorable!", date: "December 2024", tripType: "Honeymoon Package", location: "Ahmedabad" },
  { id: "12", name: "Mohammed Ali", rating: 5, text: "Group of 16 friends. Tempo Traveller was comfortable. AC excellent. Great pricing for group trips!", date: "December 2024", tripType: "Group Trip – Tempo 17", location: "Hyderabad" },
  { id: "13", name: "Lisa Anderson", rating: 5, text: "First time in India. ZipGoa made our Goa trip easy and safe. Driver spoke English well. Highly recommended!", date: "November 2024", tripType: "Goa Sightseeing", location: "Germany" },
];

export const faqs: FAQ[] = [
  { question: "How do I book a taxi with ZipGoa?", answer: "You can book in 3 ways: (1) WhatsApp us at +91 7026889254, (2) Call us directly, or (3) Fill the online booking form on our website. We confirm bookings instantly." },
  { question: "What payment methods do you accept?", answer: "We accept cash, UPI (GPay, PhonePe, Paytm), and bank transfers. Payment is usually done after the trip unless it's a pre-booked package." },
  { question: "Can I cancel or modify my booking?", answer: "Yes! Cancellations made 6+ hours before pickup are fully refundable. Modifications are accepted any time before the trip starts. WhatsApp us to modify/cancel." },
  { question: "Are your drivers verified and trained?", answer: "All our drivers are police-verified, hold valid commercial licenses, and have 5+ years of experience. They are trained in customer service and know Goa thoroughly." },
  { question: "Do you provide child seats?", answer: "Yes, we can arrange child seats on request. Please mention it while booking so we can equip the right vehicle." },
  { question: "What if my flight is delayed?", answer: "We track your flight in real-time. If your flight is delayed, our driver will wait at no extra charge. Your driver will be ready when you land." },
  { question: "Do all vehicles have air conditioning?", answer: "Yes! Every vehicle in our fleet — from the Dzire to the Urbania luxury bus — is fully air-conditioned and regularly serviced." },
  { question: "Do you do outstation trips from Goa?", answer: "Absolutely! We offer outstation trips to Mumbai, Pune, Bangalore, Hampi, Kolhapur, and more. Rates include driver allowance and toll charges." },
];

export const experienceImages = [
  { id: "1", title: "Calangute Beach", subtitle: "North Goa", gradient: "from-blue-500 to-cyan-400", emoji: "🏖️" },
  { id: "2", title: "Dudhsagar Falls", subtitle: "South Goa", gradient: "from-green-500 to-emerald-400", emoji: "🌊" },
  { id: "3", title: "Basilica of Bom Jesus", subtitle: "Old Goa", gradient: "from-orange-500 to-amber-400", emoji: "⛪" },
  { id: "4", title: "Chapora Fort", subtitle: "Vagator", gradient: "from-red-500 to-rose-400", emoji: "🏰" },
  { id: "5", title: "Anjuna Flea Market", subtitle: "Anjuna", gradient: "from-purple-500 to-violet-400", emoji: "🛍️" },
  { id: "6", title: "Goa Sunset", subtitle: "Baga Beach", gradient: "from-yellow-500 to-orange-400", emoji: "🌅" },
];

export const locations: GLocation[] = [
  {
    id: "calangute",
    image: "/images/locations/calangute.jpg",
    name: "Calangute",
    shortDesc: "Queen of Goan Beaches — North Goa's most popular tourist hub.",
    description: "Known as the 'Queen of Beaches', Calangute is North Goa's most vibrant beach destination. This bustling coastal town stretches 7km along the Arabian Sea and is home to countless beach shacks, water sports operators, and a lively nightlife scene. From Calangute, you can easily reach Baga (3km north), Anjuna (8km), and Fort Aguada (12km south).",
    area: "north",
    emoji: "🏖️",
    gradient: "from-blue-500 to-cyan-400",
    famous: ["Calangute Beach", "Water Sports", "Beach Shacks", "Nightlife"],
    bestTimeToVisit: "November to February",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 42, time: "1h 10m", prices: { dzire: 1200, ertiga: 1500, innova: 2000 } },
      { to: "Dabolim Airport (GOI)", distance: 45, time: "1h 30m", prices: { dzire: 1500, ertiga: 1800, innova: 2200 } },
      { to: "Baga Beach", distance: 3, time: "8 min", prices: { dzire: 300, ertiga: 400, innova: 500 } },
      { to: "Anjuna Beach", distance: 8, time: "20 min", prices: { dzire: 400, ertiga: 500, innova: 700 } },
      { to: "Panjim City", distance: 15, time: "30 min", prices: { dzire: 600, ertiga: 800, innova: 1100 } },
      { to: "Old Goa Churches", distance: 25, time: "45 min", prices: { dzire: 900, ertiga: 1200, innova: 1600 } },
      { to: "Dudhsagar Falls", distance: 70, time: "2h", prices: { dzire: 3500, ertiga: 4500, innova: 5500 } },
      { to: "Margao (South Goa)", distance: 55, time: "1h 30m", prices: { dzire: 1800, ertiga: 2200, innova: 3000 } },
    ],
    nearbyAttractions: [
      { name: "Baga Beach", distance: "3 km", time: "8 min", fare: 300 },
      { name: "Anjuna Beach", distance: "8 km", time: "20 min", fare: 400 },
      { name: "Fort Aguada", distance: "12 km", time: "25 min", fare: 500 },
      { name: "Chapora Fort", distance: "14 km", time: "30 min", fare: 600 },
      { name: "Panjim City", distance: "15 km", time: "30 min", fare: 600 },
      { name: "Vagator Beach", distance: "12 km", time: "25 min", fare: 500 },
    ],
    thingsToDo: ["Swimming & sunbathing", "Water sports (parasailing, jet ski, banana boat)", "Beach shack dining", "Shopping at beach market", "Nightlife at Tito's Lane", "Sunset views"],
  },
  {
    id: "baga",
    image: "/images/locations/baga.jpg",
    name: "Baga",
    shortDesc: "North Goa's party capital — beaches, clubs, and seafood.",
    description: "Baga Beach is North Goa's ultimate party destination, seamlessly connecting with Calangute to the south. Famous for lively nightlife with clubs like Tito's and Mambo's, Baga also offers excellent seafood shacks, buzzing water sports, and the iconic Saturday Night Market just a few kilometres away at Arpora.",
    area: "north",
    emoji: "🌊",
    gradient: "from-teal-500 to-blue-400",
    famous: ["Baga Beach", "Tito's Club", "Britto's Restaurant", "Saturday Night Market"],
    bestTimeToVisit: "October to March",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 39, time: "1h", prices: { dzire: 1100, ertiga: 1400, innova: 1800 } },
      { to: "Dabolim Airport (GOI)", distance: 48, time: "1h 30m", prices: { dzire: 1600, ertiga: 1900, innova: 2400 } },
      { to: "Calangute Beach", distance: 3, time: "8 min", prices: { dzire: 300, ertiga: 400, innova: 500 } },
      { to: "Anjuna Beach", distance: 7, time: "18 min", prices: { dzire: 350, ertiga: 450, innova: 600 } },
      { to: "Panjim City", distance: 17, time: "35 min", prices: { dzire: 650, ertiga: 850, innova: 1200 } },
      { to: "Old Goa Churches", distance: 28, time: "50 min", prices: { dzire: 950, ertiga: 1250, innova: 1700 } },
      { to: "Dudhsagar Falls", distance: 68, time: "2h", prices: { dzire: 3500, ertiga: 4500, innova: 5500 } },
      { to: "Chapora Fort", distance: 10, time: "22 min", prices: { dzire: 450, ertiga: 600, innova: 800 } },
    ],
    nearbyAttractions: [
      { name: "Calangute Beach", distance: "3 km", time: "8 min", fare: 300 },
      { name: "Anjuna Beach", distance: "7 km", time: "18 min", fare: 350 },
      { name: "Chapora Fort", distance: "10 km", time: "22 min", fare: 450 },
      { name: "Vagator Beach", distance: "10 km", time: "22 min", fare: 450 },
      { name: "Saturday Night Market (Arpora)", distance: "5 km", time: "12 min", fare: 300 },
      { name: "Fort Aguada", distance: "14 km", time: "28 min", fare: 550 },
    ],
    thingsToDo: ["Nightlife at Tito's & Mambo's", "Water sports (paragliding, jet ski)", "Seafood at beach shacks", "Saturday Night Market at Arpora", "Boat rides", "Sunrise walks"],
  },
  {
    id: "anjuna",
    image: "/images/locations/anjuna.jpg",
    name: "Anjuna",
    shortDesc: "Goa's bohemian heart — flea market, rocky cliffs, and sunsets.",
    description: "Anjuna is Goa's alternative soul — rocky beaches, a famous Wednesday flea market, and a laid-back bohemian culture that's been attracting travellers since the 1960s. The beach's dramatic cliff formations create beautiful sunset vantage points, while the surrounding area is dotted with yoga centres, organic cafés, and artist communities.",
    area: "north",
    emoji: "🌅",
    gradient: "from-orange-500 to-amber-400",
    famous: ["Anjuna Beach", "Wednesday Flea Market", "Rocky Cliffs", "Hippie Heritage"],
    bestTimeToVisit: "November to February",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 48, time: "1h 20m", prices: { dzire: 1400, ertiga: 1700, innova: 2300 } },
      { to: "Dabolim Airport (GOI)", distance: 53, time: "1h 40m", prices: { dzire: 1800, ertiga: 2200, innova: 2800 } },
      { to: "Calangute Beach", distance: 8, time: "20 min", prices: { dzire: 400, ertiga: 500, innova: 700 } },
      { to: "Baga Beach", distance: 7, time: "18 min", prices: { dzire: 350, ertiga: 450, innova: 600 } },
      { to: "Vagator Beach", distance: 5, time: "12 min", prices: { dzire: 300, ertiga: 400, innova: 500 } },
      { to: "Panjim City", distance: 18, time: "35 min", prices: { dzire: 700, ertiga: 900, innova: 1200 } },
      { to: "Old Goa Churches", distance: 28, time: "50 min", prices: { dzire: 950, ertiga: 1200, innova: 1600 } },
      { to: "Dudhsagar Falls", distance: 75, time: "2h 10m", prices: { dzire: 3700, ertiga: 4700, innova: 5800 } },
    ],
    nearbyAttractions: [
      { name: "Vagator Beach", distance: "5 km", time: "12 min", fare: 300 },
      { name: "Chapora Fort", distance: "7 km", time: "15 min", fare: 350 },
      { name: "Baga Beach", distance: "7 km", time: "18 min", fare: 350 },
      { name: "Calangute", distance: "8 km", time: "20 min", fare: 400 },
      { name: "Mapusa Market", distance: "13 km", time: "25 min", fare: 500 },
      { name: "Mopa Airport", distance: "48 km", time: "1h 20m", fare: 1400 },
    ],
    thingsToDo: ["Wednesday Flea Market", "Cliff-top views & sunset", "Water sports", "Yoga & meditation retreats", "Organic café culture", "Nine Bar sunset parties"],
  },
  {
    id: "panjim",
    image: "/images/locations/panjim.jpg",
    name: "Panjim",
    shortDesc: "Goa's colonial capital — Fontainhas, waterfront, and culture.",
    description: "Panjim (Panaji) is Goa's charming capital city — a blend of Portuguese colonial heritage, vibrant city life, and serene waterfront promenades along the Mandovi River. The famous Fontainhas Latin Quarter features brightly painted colonial houses that look straight out of Lisbon. Panjim is also the gateway to Old Goa's UNESCO heritage churches just 10km away.",
    area: "central",
    emoji: "🏛️",
    gradient: "from-yellow-500 to-orange-400",
    famous: ["Fontainhas Latin Quarter", "Mandovi Waterfront", "Casino Boats", "Old Goa Gateway"],
    bestTimeToVisit: "October to March",
    peakSeason: "December to February (Carnival)",
    offSeason: "June to August (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 32, time: "50 min", prices: { dzire: 900, ertiga: 1200, innova: 1600 } },
      { to: "Dabolim Airport (GOI)", distance: 29, time: "45 min", prices: { dzire: 900, ertiga: 1200, innova: 1600 } },
      { to: "Calangute Beach", distance: 15, time: "30 min", prices: { dzire: 600, ertiga: 800, innova: 1100 } },
      { to: "Old Goa", distance: 10, time: "20 min", prices: { dzire: 400, ertiga: 550, innova: 750 } },
      { to: "Anjuna Beach", distance: 18, time: "35 min", prices: { dzire: 700, ertiga: 900, innova: 1200 } },
      { to: "Margao (South Goa)", distance: 33, time: "1h", prices: { dzire: 1000, ertiga: 1300, innova: 1800 } },
      { to: "Arambol Beach", distance: 48, time: "1h 20m", prices: { dzire: 1400, ertiga: 1800, innova: 2400 } },
      { to: "Dudhsagar Falls", distance: 60, time: "1h 45m", prices: { dzire: 3200, ertiga: 4000, innova: 5000 } },
    ],
    nearbyAttractions: [
      { name: "Old Goa / Basilica Bom Jesus", distance: "10 km", time: "20 min", fare: 400 },
      { name: "Miramar Beach", distance: "3 km", time: "8 min", fare: 200 },
      { name: "Fontainhas Latin Quarter", distance: "1 km", time: "5 min", fare: 150 },
      { name: "Calangute Beach", distance: "15 km", time: "30 min", fare: 600 },
      { name: "Dona Paula Viewpoint", distance: "8 km", time: "18 min", fare: 350 },
      { name: "Mandovi River Cruise Jetty", distance: "0.5 km", time: "3 min", fare: 150 },
    ],
    thingsToDo: ["Fontainhas heritage walk", "Mandovi River cruise", "Casino boats on the river", "Old Goa churches day trip", "Goa State Museum", "Miramar Beach sunset"],
  },
  {
    id: "margao",
    name: "Margao",
    shortDesc: "South Goa's capital — markets, heritage, and authentic Goan culture.",
    description: "Margao (Madgaon) is South Goa's commercial capital and cultural hub. Unlike tourist-heavy North Goa, Margao offers an authentic slice of Goan life. Its famous covered market is one of India's best, offering everything from spices and seafood to traditional Goan sweets. The city's churches and architecture reflect centuries of Portuguese influence.",
    area: "south",
    emoji: "🛍️",
    gradient: "from-green-500 to-teal-400",
    famous: ["Covered Market", "Holy Spirit Church", "Traditional Food", "Municipal Garden"],
    bestTimeToVisit: "October to March",
    peakSeason: "December to February",
    offSeason: "June to August (Monsoon)",
    routes: [
      { to: "Dabolim Airport (GOI)", distance: 12, time: "25 min", prices: { dzire: 500, ertiga: 650, innova: 900 } },
      { to: "Mopa Airport (GOX)", distance: 62, time: "1h 30m", prices: { dzire: 1800, ertiga: 2300, innova: 3000 } },
      { to: "Panjim City", distance: 33, time: "1h", prices: { dzire: 1000, ertiga: 1300, innova: 1800 } },
      { to: "Palolem Beach", distance: 38, time: "1h", prices: { dzire: 1200, ertiga: 1500, innova: 2000 } },
      { to: "Colva Beach", distance: 7, time: "15 min", prices: { dzire: 350, ertiga: 450, innova: 600 } },
      { to: "Old Goa", distance: 28, time: "50 min", prices: { dzire: 950, ertiga: 1200, innova: 1600 } },
      { to: "Dudhsagar Falls", distance: 50, time: "1h 30m", prices: { dzire: 2500, ertiga: 3200, innova: 4200 } },
      { to: "Calangute Beach", distance: 55, time: "1h 30m", prices: { dzire: 1800, ertiga: 2200, innova: 3000 } },
    ],
    nearbyAttractions: [
      { name: "Colva Beach", distance: "7 km", time: "15 min", fare: 350 },
      { name: "Benaulim Beach", distance: "8 km", time: "18 min", fare: 400 },
      { name: "Dabolim Airport", distance: "12 km", time: "25 min", fare: 500 },
      { name: "Mangueshi Temple", distance: "15 km", time: "30 min", fare: 600 },
      { name: "Palolem Beach", distance: "38 km", time: "1h", fare: 1200 },
      { name: "Old Goa", distance: "28 km", time: "50 min", fare: 950 },
    ],
    thingsToDo: ["Margao Covered Market", "Holy Spirit Church tour", "Traditional Goan sweets", "Mangueshi Temple", "Colva Beach day trip", "Heritage architecture walk"],
  },
  {
    id: "palolem",
    image: "/images/locations/palolem.jpg",
    name: "Palolem",
    shortDesc: "South Goa's paradise crescent — serene, beautiful, and unspoiled.",
    description: "Palolem is South Goa's most beautiful beach — a perfect crescent of golden sand framed by palm trees and gentle waves. Far quieter than North Goa's bustle, Palolem attracts travellers who prefer candlelit beach dinners, morning yoga, and kayaking in calm waters to nightclub noise. The silent discos are a unique Palolem invention.",
    area: "south",
    emoji: "🌴",
    gradient: "from-emerald-500 to-green-400",
    famous: ["Crescent Beach", "Dolphin Watching", "Silent Disco", "Kayaking"],
    bestTimeToVisit: "November to February",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Dabolim Airport (GOI)", distance: 56, time: "1h 30m", prices: { dzire: 1800, ertiga: 2300, innova: 3000 } },
      { to: "Mopa Airport (GOX)", distance: 100, time: "2h 30m", prices: { dzire: 3000, ertiga: 3800, innova: 5000 } },
      { to: "Margao City", distance: 38, time: "1h", prices: { dzire: 1200, ertiga: 1500, innova: 2000 } },
      { to: "Colva Beach", distance: 42, time: "1h 10m", prices: { dzire: 1300, ertiga: 1700, innova: 2200 } },
      { to: "Panjim City", distance: 72, time: "2h", prices: { dzire: 2200, ertiga: 2800, innova: 3600 } },
      { to: "Dudhsagar Falls", distance: 60, time: "1h 45m", prices: { dzire: 2500, ertiga: 3200, innova: 4200 } },
      { to: "Agonda Beach", distance: 9, time: "20 min", prices: { dzire: 400, ertiga: 500, innova: 700 } },
      { to: "Cabo de Rama Fort", distance: 30, time: "50 min", prices: { dzire: 1000, ertiga: 1300, innova: 1700 } },
    ],
    nearbyAttractions: [
      { name: "Agonda Beach", distance: "9 km", time: "20 min", fare: 400 },
      { name: "Butterfly Beach", distance: "4 km", time: "10 min", fare: 300 },
      { name: "Cabo de Rama Fort", distance: "30 km", time: "50 min", fare: 1000 },
      { name: "Colva Beach", distance: "42 km", time: "1h 10m", fare: 1300 },
      { name: "Cotigao Wildlife Sanctuary", distance: "15 km", time: "30 min", fare: 600 },
      { name: "Dabolim Airport", distance: "56 km", time: "1h 30m", fare: 1800 },
    ],
    thingsToDo: ["Dolphin watching boat trips", "Kayaking in calm waters", "Silent disco beach parties", "Yoga retreats & sunrise yoga", "Candlelit beach dinners", "Butterfly Beach visit by boat"],
  },
  {
    id: "candolim",
    image: "/images/locations/aguada-fort.jpg",
    name: "Candolim",
    shortDesc: "North Goa's premium resort belt — Fort Aguada, calm beach, 5-star stays.",
    description: "Candolim is North Goa's most premium beach destination — home to 5-star resorts, the iconic Fort Aguada, and a calm beach that attracts families and luxury travellers. Just 12km from Panjim with excellent access to Calangute and Baga, Candolim is the ideal base for exploring North Goa without the chaos.",
    area: "north",
    emoji: "⛵",
    gradient: "from-sky-500 to-blue-400",
    famous: ["Fort Aguada", "Sinquerim Beach", "Luxury Resorts", "Watersports"],
    bestTimeToVisit: "October to March",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 40, time: "1h 5m", prices: { dzire: 1150, ertiga: 1450, innova: 1900 } },
      { to: "Dabolim Airport (GOI)", distance: 43, time: "1h 20m", prices: { dzire: 1400, ertiga: 1750, innova: 2200 } },
      { to: "Calangute Beach", distance: 5, time: "10 min", prices: { dzire: 300, ertiga: 400, innova: 500 } },
      { to: "Panjim City", distance: 12, time: "25 min", prices: { dzire: 500, ertiga: 700, innova: 950 } },
      { to: "Anjuna Beach", distance: 15, time: "30 min", prices: { dzire: 600, ertiga: 800, innova: 1100 } },
      { to: "Old Goa", distance: 22, time: "40 min", prices: { dzire: 800, ertiga: 1000, innova: 1400 } },
      { to: "Baga Beach", distance: 7, time: "15 min", prices: { dzire: 350, ertiga: 450, innova: 600 } },
      { to: "Dudhsagar Falls", distance: 72, time: "2h 10m", prices: { dzire: 3600, ertiga: 4600, innova: 5700 } },
    ],
    nearbyAttractions: [
      { name: "Fort Aguada", distance: "2 km", time: "5 min", fare: 200 },
      { name: "Sinquerim Beach", distance: "1 km", time: "3 min", fare: 150 },
      { name: "Calangute Beach", distance: "5 km", time: "10 min", fare: 300 },
      { name: "Baga Beach", distance: "7 km", time: "15 min", fare: 350 },
      { name: "Panjim City", distance: "12 km", time: "25 min", fare: 500 },
      { name: "Miramar Beach", distance: "10 km", time: "22 min", fare: 450 },
    ],
    thingsToDo: ["Fort Aguada exploration", "Sinquerim beach water sports", "Scuba diving & snorkelling", "Sunset cruises on the Arabian Sea", "Luxury resort dining", "North Goa day trips"],
  },
  {
    id: "vagator",
    image: "/images/locations/vagator.jpg",
    name: "Vagator",
    shortDesc: "Chapora Fort, cliffside views, and Goa's alternative party scene.",
    description: "Vagator is where Goa's alternative scene meets stunning natural beauty. Chapora Fort — made famous by Dil Chahta Hai — watches over the beach from dramatic red laterite cliffs. Little Vagator (Ozran Beach) is one of Goa's most photogenic spots, while the area is home to legendary party venues and a thriving artist community.",
    area: "north",
    emoji: "🏰",
    gradient: "from-red-500 to-rose-400",
    famous: ["Chapora Fort", "Little Vagator Beach", "Cliffside Views", "Hilltop Parties"],
    bestTimeToVisit: "November to February",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 45, time: "1h 15m", prices: { dzire: 1300, ertiga: 1600, innova: 2100 } },
      { to: "Dabolim Airport (GOI)", distance: 56, time: "1h 40m", prices: { dzire: 1800, ertiga: 2200, innova: 2900 } },
      { to: "Anjuna Beach", distance: 5, time: "12 min", prices: { dzire: 300, ertiga: 400, innova: 500 } },
      { to: "Calangute Beach", distance: 12, time: "25 min", prices: { dzire: 500, ertiga: 700, innova: 900 } },
      { to: "Panjim City", distance: 22, time: "40 min", prices: { dzire: 800, ertiga: 1000, innova: 1400 } },
      { to: "Old Goa", distance: 32, time: "55 min", prices: { dzire: 1000, ertiga: 1300, innova: 1800 } },
      { to: "Arambol Beach", distance: 24, time: "45 min", prices: { dzire: 850, ertiga: 1100, innova: 1500 } },
      { to: "Dudhsagar Falls", distance: 78, time: "2h 15m", prices: { dzire: 3800, ertiga: 4800, innova: 6000 } },
    ],
    nearbyAttractions: [
      { name: "Chapora Fort", distance: "1 km", time: "3 min", fare: 150 },
      { name: "Little Vagator (Ozran) Beach", distance: "0.5 km", time: "2 min", fare: 150 },
      { name: "Anjuna Beach", distance: "5 km", time: "12 min", fare: 300 },
      { name: "Baga Beach", distance: "10 km", time: "22 min", fare: 450 },
      { name: "Morjim Beach", distance: "15 km", time: "30 min", fare: 600 },
      { name: "Mapusa Market", distance: "12 km", time: "25 min", fare: 500 },
    ],
    thingsToDo: ["Chapora Fort (Dil Chahta Hai!)", "Cliff diving at Ozran", "Sunset at Little Vagator", "Hilltop & Nyex party nights", "Sunrise yoga", "Morjim beach drive"],
  },
  {
    id: "old-goa",
    name: "Old Goa",
    shortDesc: "UNESCO World Heritage Site — Goa's magnificent Portuguese-era churches.",
    description: "Old Goa (Velha Goa) is Goa's most important heritage destination — a UNESCO World Heritage Site with a concentration of 16th and 17th century Portuguese churches unmatched anywhere in Asia. The Basilica of Bom Jesus, housing St. Francis Xavier's remains, draws pilgrims and tourists from across the world. The architecture rivals any European cathedral.",
    area: "central",
    emoji: "⛪",
    gradient: "from-amber-600 to-yellow-500",
    famous: ["Basilica of Bom Jesus", "Se Cathedral", "Church of St. Cajetan", "UNESCO Heritage"],
    bestTimeToVisit: "October to March",
    peakSeason: "November to February (St. Francis Xavier feast: December)",
    offSeason: "June to August (Monsoon)",
    routes: [
      { to: "Mopa Airport (GOX)", distance: 42, time: "1h 5m", prices: { dzire: 1200, ertiga: 1500, innova: 2000 } },
      { to: "Dabolim Airport (GOI)", distance: 22, time: "40 min", prices: { dzire: 750, ertiga: 950, innova: 1300 } },
      { to: "Panjim City", distance: 10, time: "20 min", prices: { dzire: 400, ertiga: 550, innova: 750 } },
      { to: "Calangute Beach", distance: 25, time: "45 min", prices: { dzire: 900, ertiga: 1200, innova: 1600 } },
      { to: "Margao (South Goa)", distance: 28, time: "50 min", prices: { dzire: 950, ertiga: 1200, innova: 1600 } },
      { to: "Anjuna Beach", distance: 28, time: "50 min", prices: { dzire: 950, ertiga: 1200, innova: 1600 } },
      { to: "Colva Beach", distance: 33, time: "55 min", prices: { dzire: 1100, ertiga: 1400, innova: 1900 } },
      { to: "Dudhsagar Falls", distance: 50, time: "1h 30m", prices: { dzire: 2500, ertiga: 3200, innova: 4200 } },
    ],
    nearbyAttractions: [
      { name: "Basilica of Bom Jesus", distance: "0.2 km", time: "In area", fare: 0 },
      { name: "Se Cathedral", distance: "0.3 km", time: "5 min walk", fare: 0 },
      { name: "Archaeological Museum Goa", distance: "0.5 km", time: "5 min walk", fare: 0 },
      { name: "Panjim City", distance: "10 km", time: "20 min", fare: 400 },
      { name: "Pilar Seminary", distance: "7 km", time: "15 min", fare: 350 },
      { name: "Dabolim Airport", distance: "22 km", time: "40 min", fare: 750 },
    ],
    thingsToDo: ["Basilica of Bom Jesus (St. Xavier's relics)", "Se Cathedral — Asia's largest church", "Archaeology Museum Goa", "Church of St. Cajetan", "Heritage site walk", "Photography of colonial architecture"],
  },
  {
    id: "colva",
    name: "Colva",
    shortDesc: "South Goa's longest beach — peaceful, clean, and crowd-free.",
    description: "Colva is South Goa's most popular beach — a vast, uncrowded stretch of fine white sand stretching 25km along the coast. Unlike North Goa's bustle, Colva offers a peaceful beach experience with excellent seafood, gentle waves for swimming, and the historic Menino Jesus Church drawing pilgrims. Perfect for long evening walks.",
    area: "south",
    emoji: "🌊",
    gradient: "from-cyan-500 to-blue-400",
    famous: ["Colva Beach", "Menino Jesus Church", "Watersports", "South Goa Vibes"],
    bestTimeToVisit: "November to February",
    peakSeason: "November to January",
    offSeason: "June to September (Monsoon)",
    routes: [
      { to: "Dabolim Airport (GOI)", distance: 14, time: "30 min", prices: { dzire: 550, ertiga: 700, innova: 950 } },
      { to: "Mopa Airport (GOX)", distance: 70, time: "1h 45m", prices: { dzire: 2100, ertiga: 2600, innova: 3400 } },
      { to: "Margao City", distance: 7, time: "15 min", prices: { dzire: 350, ertiga: 450, innova: 600 } },
      { to: "Panjim City", distance: 38, time: "1h 10m", prices: { dzire: 1200, ertiga: 1500, innova: 2000 } },
      { to: "Palolem Beach", distance: 42, time: "1h 10m", prices: { dzire: 1300, ertiga: 1700, innova: 2200 } },
      { to: "Calangute Beach", distance: 52, time: "1h 25m", prices: { dzire: 1700, ertiga: 2100, innova: 2800 } },
      { to: "Old Goa", distance: 33, time: "55 min", prices: { dzire: 1100, ertiga: 1400, innova: 1900 } },
      { to: "Dudhsagar Falls", distance: 45, time: "1h 20m", prices: { dzire: 2200, ertiga: 2800, innova: 3600 } },
    ],
    nearbyAttractions: [
      { name: "Benaulim Beach", distance: "2 km", time: "5 min", fare: 200 },
      { name: "Margao City", distance: "7 km", time: "15 min", fare: 350 },
      { name: "Menino Jesus Church", distance: "0.5 km", time: "3 min", fare: 150 },
      { name: "Dabolim Airport", distance: "14 km", time: "30 min", fare: 550 },
      { name: "Palolem Beach", distance: "42 km", time: "1h 10m", fare: 1300 },
      { name: "Dudhsagar Falls", distance: "45 km", time: "1h 20m", fare: 2200 },
    ],
    thingsToDo: ["Long beach walks on 25km shoreline", "Water sports & beach activities", "Menino Jesus Church visit", "Seafood dining at beach shacks", "Sunset views", "South Goa sightseeing"],
  },
];

export const selfDriveVehicles: SelfDriveVehicle[] = [
  // â”€â”€ ECONOMY HATCHBACKS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "swift-manual",
    name: "Maruti Swift New (Manual)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/swift.jpg",
    pricePerDay: 1200,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "16 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 3000,
    features: ["AC", "Music System", "Power Steering", "Central Locking"],
  },
  {
    id: "swift-automatic",
    name: "Maruti Swift New (Automatic)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/swift.jpg",
    pricePerDay: 1600,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "16 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 3500,
    features: ["AC", "Music System", "Power Steering", "Central Locking"],
  },
  {
    id: "baleno-manual",
    name: "Maruti Baleno New (Manual)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/baleno.jpg",
    pricePerDay: 1300,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "18 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 3000,
    features: ["AC", "Touchscreen", "Power Steering", "Rear Camera"],
  },
  {
    id: "baleno-automatic",
    name: "Maruti Baleno New (Automatic)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/baleno.jpg",
    pricePerDay: 1800,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "18 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 4000,
    features: ["AC", "Touchscreen", "Power Steering", "Rear Camera"],
  },
  {
    id: "i20-manual",
    name: "Hyundai i20 New (Manual)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/i20.jpg",
    pricePerDay: 1500,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "16 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 3500,
    features: ["AC", "Sunroof", "Touchscreen", "Rear Camera"],
  },
  {
    id: "i20-automatic",
    name: "Hyundai i20 New (Automatic)",
    type: "Hatchback",
    category: "self-drive",
    segment: "economy",
    image: "/images/self-drive/i20.jpg",
    pricePerDay: 1800,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "16 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 4000,
    features: ["AC", "Sunroof", "Touchscreen", "Rear Camera"],
  },
  // â”€â”€ SEDANS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "dzire-manual",
    name: "Swift Dzire New (Manual)",
    type: "Sedan",
    category: "self-drive",
    segment: "sedan",
    image: "/images/self-drive/dzire.jpg",
    pricePerDay: 1500,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "18 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 3500,
    features: ["AC", "Music System", "Power Steering", "Large Boot"],
  },
  {
    id: "dzire-automatic",
    name: "Swift Dzire New (Automatic)",
    type: "Sedan",
    category: "self-drive",
    segment: "sedan",
    image: "/images/self-drive/dzire.jpg",
    pricePerDay: 1800,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "15 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 4000,
    features: ["AC", "Music System", "Power Steering", "Large Boot"],
  },
  // â”€â”€ SUVs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "creta-manual",
    name: "Hyundai Creta New (Manual)",
    type: "SUV",
    category: "self-drive",
    segment: "suv",
    image: "/images/self-drive/creta.jpg",
    pricePerDay: 2500,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "15 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    deposit: 5000,
    features: ["Sunroof", "AC", "Touchscreen", "Reverse Camera"],
  },
  {
    id: "creta-automatic",
    name: "Creta New Automatic — Panoramic Sunroof",
    type: "SUV",
    category: "self-drive",
    segment: "suv",
    image: "/images/self-drive/creta.jpg",
    pricePerDay: 3500,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "15 kmpl",
    seats: 5,
    doors: 4,
    isNewModel: true,
    isPremium: true,
    deposit: 6000,
    features: ["Panoramic Sunroof", "Premium Interior", "ADAS Safety", "Wireless Charging"],
  },
  // â”€â”€ 7-SEATERS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "ertiga-manual",
    name: "Maruti Ertiga New 7-Seater (Manual)",
    type: "7 Seater MPV",
    category: "self-drive",
    segment: "family",
    image: "/images/self-drive/ertiga.jpg",
    pricePerDay: 2200,
    transmission: "Manual",
    fuelType: "Petrol",
    mileage: "18 kmpl",
    seats: 7,
    doors: 5,
    isNewModel: true,
    deposit: 5000,
    features: ["AC", "3-Row Seating", "Music System", "Power Windows"],
  },
  {
    id: "ertiga-automatic",
    name: "Maruti Ertiga New 7-Seater (Automatic)",
    type: "7 Seater MPV",
    category: "self-drive",
    segment: "family",
    image: "/images/self-drive/ertiga.jpg",
    pricePerDay: 2800,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "15 kmpl",
    seats: 7,
    doors: 5,
    isNewModel: true,
    deposit: 6000,
    features: ["AC", "3-Row Seating", "Touchscreen", "Rear AC Vents"],
  },
  {
    id: "innova-crysta-manual",
    name: "Toyota Innova Crysta (Manual)",
    type: "7 Seater Premium MPV",
    category: "self-drive",
    segment: "family",
    image: "/images/self-drive/innova-crysta.jpg",
    pricePerDay: 3000,
    transmission: "Manual",
    fuelType: "Diesel",
    mileage: "14 kmpl",
    seats: 7,
    doors: 5,
    isNewModel: true,
    deposit: 6000,
    features: ["AC", "Captain Seats", "Touchscreen", "Curtain Airbags"],
  },
  {
    id: "innova-crysta-automatic",
    name: "Toyota Innova Crysta (Automatic)",
    type: "7 Seater Premium MPV",
    category: "self-drive",
    segment: "family",
    image: "/images/self-drive/innova-crysta.jpg",
    pricePerDay: 3500,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "14 kmpl",
    seats: 7,
    doors: 5,
    isNewModel: true,
    isPremium: true,
    deposit: 7000,
    features: ["AC", "Captain Seats", "Premium Interior", "360° Camera"],
  },
  {
    id: "innova-hycross",
    name: "Toyota Innova Hycross Hybrid",
    type: "7 Seater Hybrid MPV",
    category: "self-drive",
    segment: "family",
    image: "/images/self-drive/hycross.jpg",
    pricePerDay: 4000,
    transmission: "Automatic",
    fuelType: "Petrol Hybrid",
    mileage: "18 kmpl",
    seats: 7,
    doors: 5,
    isNewModel: true,
    isPremium: true,
    deposit: 8000,
    features: ["Hybrid Engine", "Panoramic Sunroof", "Captain Seats", "ADAS", "Wireless Charging"],
  },
  // â”€â”€ ADVENTURE â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "thar-manual-hardtop",
    name: "Mahindra Thar New (Manual) Hard Top",
    type: "4x4 SUV",
    category: "self-drive",
    segment: "adventure",
    image: "/images/self-drive/thar-hardtop.jpg",
    pricePerDay: 3500,
    transmission: "Manual",
    fuelType: "Diesel",
    mileage: "15 kmpl",
    seats: 4,
    doors: 3,
    isNewModel: true,
    deposit: 7000,
    features: ["4x4 Drive", "Hard Top", "Off-Road Tyres", "Adventure Ready"],
  },
  {
    id: "thar-auto-hardtop",
    name: "Mahindra Thar New (Automatic) Hard Top",
    type: "4x4 SUV",
    category: "self-drive",
    segment: "adventure",
    image: "/images/self-drive/thar-auto-hardtop.jpg",
    pricePerDay: 3500,
    transmission: "Automatic",
    fuelType: "Diesel",
    mileage: "15 kmpl",
    seats: 4,
    doors: 3,
    isNewModel: true,
    deposit: 7000,
    features: ["4x4 Drive", "Hard Top", "Off-Road Tyres", "Waterproof Seats"],
  },
  {
    id: "thar-convertible",
    name: "Mahindra Thar Convertible 4x4 (Soft Top)",
    type: "4x4 Convertible",
    category: "self-drive",
    segment: "adventure",
    image: "/images/self-drive/thar-convertible.jpg",
    pricePerDay: 4000,
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: "15 kmpl",
    seats: 4,
    doors: 3,
    isNewModel: true,
    isPremium: true,
    deposit: 8000,
    features: ["Soft Top Convertible", "4x4 Drive", "Open-Air Driving", "Beach Ready"],
  },
  {
    id: "thar-convertible-manual",
    name: "Mahindra Thar Convertible 4x4 (Manual Soft Top)",
    type: "4x4 Convertible",
    category: "self-drive",
    segment: "adventure",
    image: "/images/self-drive/thar-convertible.jpg",
    pricePerDay: 3500,
    transmission: "Manual",
    fuelType: "Diesel",
    mileage: "15 kmpl",
    seats: 4,
    doors: 3,
    isNewModel: true,
    deposit: 7000,
    features: ["Soft Top Convertible", "4x4 Drive", "Open-Air Driving", "Beach Ready"],
  },
];

